Repository GabrielaMedrado/SAP007-social-network, pull requests merged in 2022-04, with the labels that each got.

#22 feat:show post
  src/js/pages/feed.js
  src/lib/config-firestore.js
Labels: feat

#23 docs:created components and writePost page
  src/js/components/footer.js
  src/js/components/header.js
  src/js/components/post.js
  src/js/pages/feed.js
  src/js/pages/writePost.js
  src/js/routes.js
Labels: documentation

#24 Feat/style page register
  src/img/logo.png
  src/js/pages/register.js
  src/js/pages/signIn.js
  src/style/pages/register.css
  src/style/pages/signIn.css
Labels: style

#25 style:
  src/img/icon-confirm.png
  src/img/icon-delete.png
  src/img/icon-edit.png
  src/img/icon-goodfood.png
  src/img/icon-like-empty.png
  src/img/icon-like.png
  src/index.html
  src/js/components/post.js
  src/js/pages/feed.js
  src/js/pages/writePost.js
  src/style/components/post.css
  src/style/global.css
  src/style/variables.css
Labels: style

#26 Refactor/rename functions
  src/js/components/post.js
  src/js/pages/feed.js
  src/js/pages/writePost.js
  src/lib/config-auth.js
  src/lib/config-firestore.js
  src/style/global.css
  src/style/pages/writePost.css
Labels: refactor

#27 style: feed page navigation menu
  src/img/icon-home.png
  src/img/icon-logout.png
  src/img/icon-new-post.png
  src/js/components/navbar.js
  src/js/pages/feed.js
  src/style/components/navbar.css
  src/style/global.css
Labels: style

#28 style: header feed page
  src/img/logo-header.png
  src/js/components/header.js
  src/js/pages/feed.js
  src/style/components/header.css
  src/style/global.css
Labels: style

#29 style: header feed page
  src/js/pages/feed.js
  src/style/components/header.css
  src/style/components/post.css
  src/style/pages/feed.css
Labels: style

#31 style:page-write-post
  src/js/pages/writePost.js
  src/style/pages/writePost.css
Labels: style

#32 style:page-write-post-add-navbar
  src/js/pages/writePost.js
Labels: style

#33 chore:organized-page
  src/js/components/post.js
Labels: chore

#34 feat format date and order feed
  src/js/components/post.js
  src/lib/config-firestore.js
Labels: feat

#35 feat:function-deletePost
  src/js/components/post.js
  src/lib/config-firestore.js
Labels: feat

#36 Feat/function like
  src/js/components/post.js
  src/lib/config-firestore.js
Labels: feat

#38 feat: add edit function
  src/js/components/post.js
  src/lib/config-firestore.js
Labels: feat

#39 fix: edit button
  src/js/components/post.js
Labels: bug

#40 Fix: image deploy
  src/js/components/header.js
  src/js/components/navbar.js
Labels: bug

#41 fix routes
  src/js/pages/register.js
  src/js/pages/signIn.js
Labels: bug

#42 feat:delete-edit-author-only
  src/js/components/post.js
Labels: feat

#43 feat:post-confirm-deletion
  src/js/components/post.js
  src/js/pages/feed.js
  src/style/components/post.css
Labels: feat

#44 fix logged user and routes
  src/js/routes.js
  src/lib/config-auth.js
Labels: bug

#46 Feat/function like
  package.json
  src/js/components/post.js
  src/lib/config-firestore.js
  src/style/components/post.css
Labels: feat

#49 Test/component post
  .eslintrc
  src/js/components/header.js
  src/js/components/navbar.js
  src/js/components/post.js
  src/js/pages/feed.js
  src/js/pages/register.js
  src/js/pages/signIn.js
  src/js/pages/writePost.js
  src/js/routes.js
  src/lib/__mocks__/exports.js
  src/lib/config-auth.js
  src/lib/config-firebase.js
  src/lib/config-firestore.js
  src/lib/exports.js
  test/index.spec.js
  test/js/routes.spec.js
  test/lib/config-auth.spec.js
  test/lib/config-firestore.spec.js
  test/pages/feed.spec.js
  test/pages/register.spec.js
  test/pages/signIn.spec.js
  test/pages/writePost.spec.js
Labels: bug

#50 Feat/add user name
  src/js/components/post.js
  src/js/pages/register.js
  src/js/pages/signIn.js
  src/js/pages/writePost.js
  src/lib/__mocks__/exports.js
  src/lib/config-auth.js
  src/lib/config-firebase.js
  src/lib/config-firestore.js
  src/lib/exports.js
  src/style/components/post.css
  test/js/components/post.spec.js
  test/lib/config-auth.spec.js
  test/pages/register.spec.js
Labels: feat
