Repository GabrielaMedrado/SAP007-social-network, pull requests merged in 2022-03, with the labels that each got.

#10 feat: add-createPost
  src/lib/config-firestore.js
Labels: feat

#11 docs: organized-files
  src/pages/feed/index.js
  src/pages/register/index.js
  src/pages/signIn/index.js
Labels: documentation

#12 docs: organized routes
  src/routes.js
Labels: feat

#14 Docs/organized files
  src/pages/register/index.js
  src/pages/signIn/index.js
Labels: documentation

#15 docs: organized files
  src/pages/register/index.js
  src/pages/signIn/index.js
Labels: documentation

#16 refactor logout
  src/lib/config-auth.js
  src/pages/feed/index.js
  src/pages/signIn/index.js
Labels: refactor

#17 refactor:Adjustment routes
  src/lib/config-auth.js
  src/lib/config-firestore.js
  src/routes.js
Labels: refactor

#18 style: pages
  src/img/goodfood.png
  src/index.html
  src/pages/feed/index.js
  src/pages/register/index.js
  src/pages/signIn/index.js
  src/style/feed.css
  src/style/global.css
  src/style/register.css
  src/style/signIn.css
  src/style/style.css
  src/style/variables.css
Labels: style

#20 docs: template-feed
  src/js/pages/feed.js
  src/lib/config-firestore.js
Labels: documentation

#21 feat:function-getDoc
  src/js/pages/feed.js
  src/js/pages/register.js
  src/js/routes.js
  src/lib/config-firestore.js
Labels: feat
